spring.application.name=medical-clinic-proxy
server.port=9090
spring.cloud.openfeign.client.config.postClient.url=http://localhost:8080/visits
spring.cloud.openfeign.okhttp.enabled=true
feign.client.config.default.loggerLevel=full
logging.level.com.example.medical_clinic_proxy.client=debug
spring.cloud.openfeign.circuitbreaker.enabled=true